version: '2.4'

services:

 Boinc:
  container_name: boinc
  image: volaricsi/boinc
  restart: always

#  logging:
#      driver: syslog
#      options:
#        tag: "{{.Name}}"


  mem_limit: 5g

  ports:
    - 31416:31416

  volumes:
    - /home/boinc/:/config

  environment:
    # Boinc user
    - PUID=2001
    - PGID=2001

  network_mode: host
